### PR TITLE
Add migration for publisher keywords

### PR DESCRIPTION
**Pull request by simonv3**
@Floppy I think this is what you're asking for, but I'm not sure whether migrations actually work that way - does this need to be in a new migration?

### CODE REVIEW

**Comment by Floppy** [comment]
Ah, yes, it'll need to be in a new one, otherwise the thing won't know to run it. Want me to move it over?

**Comment by simonv3** [comment]
@Floppy Sure if you have time!

**Comment by Floppy** [comment]
Not sure I will today, but we'll see.

**Comment by Floppy** [comment]
Actually I will do this now, then I can close off the story and tidy my mind a little :)

**Comment by simonv3** [comment]
Haha, thanks!


—

**Pull request merged**
